// CcSocketRef：CC socket 对拍参考顶层 = SocketDevSide + SocketIcnSide
// 背对背（PDC 线交叉直连），对齐 XiangShan Top 中 connectCHIToZhuJiang 的
// socketIO <> socket.io.socket 连接（Top.scala:552 的集成形态；kunminghu-v3
// CC 节点 socket="sync"，两侧同 clock/reset）。
//
// 边界：
//   l2_*   = SocketDevSide io_icn_*（桥/L2 侧；rx=inject 输入、tx=eject 输出。
//           io_icn_tx_req 在 RTL 中被桥恒置 ready=false，firtool 已裁掉该口，
//           故 l2_tx_req 在此不存在——eject REQ 的死端反压经 PDC token 自然
//           体现在 ring_tx_req_ready 上，对拍时 ring 侧激励该通道即可）
//   ring_* = SocketIcnSide io_dev_*（环侧；tx=inject 输出、rx=eject 输入）
//
// 本文件为对拍基础设施（手写，端口名由 verilator 编译期核对）。
module CcSocketRef(
  input clock,
  input reset,
  // ---- L2 侧（SocketDevSide io_icn_*）----
  output        l2_rx_req_ready,
  input         l2_rx_req_valid,
  input         l2_rx_req_bits_ExpCompAck,
  input         l2_rx_req_bits_Excl,
  input         l2_rx_req_bits_SnpAttr,
  input  [3:0]  l2_rx_req_bits_MemAttr,
  input  [1:0]  l2_rx_req_bits_Order,
  input  [47:0] l2_rx_req_bits_Addr,
  input  [2:0]  l2_rx_req_bits_Size,
  input  [6:0]  l2_rx_req_bits_Opcode,
  input  [11:0] l2_rx_req_bits_TxnID,
  input  [10:0] l2_rx_req_bits_SrcID,
  input  [10:0] l2_rx_req_bits_TgtID,
  input  [3:0]  l2_rx_req_bits_QoS,
  output        l2_rx_resp_ready,
  input         l2_rx_resp_valid,
  input  [11:0] l2_rx_resp_bits_DBID,
  input  [2:0]  l2_rx_resp_bits_CBusy,
  input  [2:0]  l2_rx_resp_bits_FwdState,
  input  [2:0]  l2_rx_resp_bits_Resp,
  input  [1:0]  l2_rx_resp_bits_RespErr,
  input  [4:0]  l2_rx_resp_bits_Opcode,
  input  [11:0] l2_rx_resp_bits_TxnID,
  input  [10:0] l2_rx_resp_bits_SrcID,
  input  [10:0] l2_rx_resp_bits_TgtID,
  input  [3:0]  l2_rx_resp_bits_QoS,
  output        l2_rx_data_ready,
  input         l2_rx_data_valid,
  input  [255:0] l2_rx_data_bits_Data,
  input  [31:0] l2_rx_data_bits_BE,
  input  [1:0]  l2_rx_data_bits_DataID,
  input  [15:0] l2_rx_data_bits_DBID,
  input  [2:0]  l2_rx_data_bits_CBusy,
  input  [7:0]  l2_rx_data_bits_DataSource,
  input  [2:0]  l2_rx_data_bits_Resp,
  input  [1:0]  l2_rx_data_bits_RespErr,
  input  [3:0]  l2_rx_data_bits_Opcode,
  input  [10:0] l2_rx_data_bits_HomeNID,
  input  [11:0] l2_rx_data_bits_TxnID,
  input  [10:0] l2_rx_data_bits_SrcID,
  input  [10:0] l2_rx_data_bits_TgtID,
  input  [3:0]  l2_rx_data_bits_QoS,
  input         l2_tx_resp_ready,
  output        l2_tx_resp_valid,
  output [11:0] l2_tx_resp_bits_DBID,
  output [2:0]  l2_tx_resp_bits_CBusy,
  output [2:0]  l2_tx_resp_bits_FwdState,
  output [2:0]  l2_tx_resp_bits_Resp,
  output [1:0]  l2_tx_resp_bits_RespErr,
  output [4:0]  l2_tx_resp_bits_Opcode,
  output [11:0] l2_tx_resp_bits_TxnID,
  output [10:0] l2_tx_resp_bits_SrcID,
  output [3:0]  l2_tx_resp_bits_QoS,
  input         l2_tx_data_ready,
  output        l2_tx_data_valid,
  output [255:0] l2_tx_data_bits_Data,
  output [31:0] l2_tx_data_bits_BE,
  output [1:0]  l2_tx_data_bits_DataID,
  output [15:0] l2_tx_data_bits_DBID,
  output [2:0]  l2_tx_data_bits_CBusy,
  output [7:0]  l2_tx_data_bits_DataSource,
  output [2:0]  l2_tx_data_bits_Resp,
  output [1:0]  l2_tx_data_bits_RespErr,
  output [3:0]  l2_tx_data_bits_Opcode,
  output [10:0] l2_tx_data_bits_HomeNID,
  output [11:0] l2_tx_data_bits_TxnID,
  output [10:0] l2_tx_data_bits_SrcID,
  output [10:0] l2_tx_data_bits_TgtID,
  output [3:0]  l2_tx_data_bits_QoS,
  input         l2_tx_snoop_ready,
  output        l2_tx_snoop_valid,
  output        l2_tx_snoop_bits_RetToSrc,
  output        l2_tx_snoop_bits_DoNotGoToSD,
  output [44:0] l2_tx_snoop_bits_Addr,
  output [4:0]  l2_tx_snoop_bits_Opcode,
  output [11:0] l2_tx_snoop_bits_FwdTxnID,
  output [10:0] l2_tx_snoop_bits_FwdNID,
  output [11:0] l2_tx_snoop_bits_TxnID,
  output [10:0] l2_tx_snoop_bits_SrcID,
  output [3:0]  l2_tx_snoop_bits_QoS,
  // ---- 环侧（SocketIcnSide io_dev_*）----
  input         ring_rx_req_ready,
  output        ring_rx_req_valid,
  output        ring_rx_req_bits_ExpCompAck,
  output        ring_rx_req_bits_Excl,
  output        ring_rx_req_bits_SnpAttr,
  output [3:0]  ring_rx_req_bits_MemAttr,
  output [1:0]  ring_rx_req_bits_Order,
  output [47:0] ring_rx_req_bits_Addr,
  output [2:0]  ring_rx_req_bits_Size,
  output [6:0]  ring_rx_req_bits_Opcode,
  output [11:0] ring_rx_req_bits_TxnID,
  output [10:0] ring_rx_req_bits_SrcID,
  output [10:0] ring_rx_req_bits_TgtID,
  output [3:0]  ring_rx_req_bits_QoS,
  input         ring_rx_resp_ready,
  output        ring_rx_resp_valid,
  output [11:0] ring_rx_resp_bits_DBID,
  output [2:0]  ring_rx_resp_bits_CBusy,
  output [2:0]  ring_rx_resp_bits_FwdState,
  output [2:0]  ring_rx_resp_bits_Resp,
  output [1:0]  ring_rx_resp_bits_RespErr,
  output [4:0]  ring_rx_resp_bits_Opcode,
  output [11:0] ring_rx_resp_bits_TxnID,
  output [10:0] ring_rx_resp_bits_SrcID,
  output [10:0] ring_rx_resp_bits_TgtID,
  output [3:0]  ring_rx_resp_bits_QoS,
  input         ring_rx_data_ready,
  output        ring_rx_data_valid,
  output [255:0] ring_rx_data_bits_Data,
  output [31:0] ring_rx_data_bits_BE,
  output [1:0]  ring_rx_data_bits_DataID,
  output [15:0] ring_rx_data_bits_DBID,
  output [2:0]  ring_rx_data_bits_CBusy,
  output [7:0]  ring_rx_data_bits_DataSource,
  output [2:0]  ring_rx_data_bits_Resp,
  output [1:0]  ring_rx_data_bits_RespErr,
  output [3:0]  ring_rx_data_bits_Opcode,
  output [10:0] ring_rx_data_bits_HomeNID,
  output [11:0] ring_rx_data_bits_TxnID,
  output [10:0] ring_rx_data_bits_SrcID,
  output [10:0] ring_rx_data_bits_TgtID,
  output [3:0]  ring_rx_data_bits_QoS,
  output        ring_tx_req_ready,
  input         ring_tx_req_valid,
  input         ring_tx_req_bits_ExpCompAck,
  input         ring_tx_req_bits_Excl,
  input         ring_tx_req_bits_SnpAttr,
  input  [3:0]  ring_tx_req_bits_MemAttr,
  input  [1:0]  ring_tx_req_bits_Order,
  input  [47:0] ring_tx_req_bits_Addr,
  input  [2:0]  ring_tx_req_bits_Size,
  input  [6:0]  ring_tx_req_bits_Opcode,
  input  [11:0] ring_tx_req_bits_TxnID,
  input  [10:0] ring_tx_req_bits_SrcID,
  input  [10:0] ring_tx_req_bits_TgtID,
  input  [3:0]  ring_tx_req_bits_QoS,
  output        ring_tx_resp_ready,
  input         ring_tx_resp_valid,
  input  [11:0] ring_tx_resp_bits_DBID,
  input  [2:0]  ring_tx_resp_bits_CBusy,
  input  [2:0]  ring_tx_resp_bits_FwdState,
  input  [2:0]  ring_tx_resp_bits_Resp,
  input  [1:0]  ring_tx_resp_bits_RespErr,
  input  [4:0]  ring_tx_resp_bits_Opcode,
  input  [11:0] ring_tx_resp_bits_TxnID,
  input  [10:0] ring_tx_resp_bits_SrcID,
  input  [10:0] ring_tx_resp_bits_TgtID,
  input  [3:0]  ring_tx_resp_bits_QoS,
  output        ring_tx_data_ready,
  input         ring_tx_data_valid,
  input  [255:0] ring_tx_data_bits_Data,
  input  [31:0] ring_tx_data_bits_BE,
  input  [1:0]  ring_tx_data_bits_DataID,
  input  [15:0] ring_tx_data_bits_DBID,
  input  [2:0]  ring_tx_data_bits_CBusy,
  input  [7:0]  ring_tx_data_bits_DataSource,
  input  [2:0]  ring_tx_data_bits_Resp,
  input  [1:0]  ring_tx_data_bits_RespErr,
  input  [3:0]  ring_tx_data_bits_Opcode,
  input  [10:0] ring_tx_data_bits_HomeNID,
  input  [11:0] ring_tx_data_bits_TxnID,
  input  [10:0] ring_tx_data_bits_SrcID,
  input  [10:0] ring_tx_data_bits_TgtID,
  input  [3:0]  ring_tx_data_bits_QoS,
  output        ring_tx_snoop_ready,
  input         ring_tx_snoop_valid,
  input         ring_tx_snoop_bits_RetToSrc,
  input         ring_tx_snoop_bits_DoNotGoToSD,
  input  [44:0] ring_tx_snoop_bits_Addr,
  input  [4:0]  ring_tx_snoop_bits_Opcode,
  input  [11:0] ring_tx_snoop_bits_FwdTxnID,
  input  [10:0] ring_tx_snoop_bits_FwdNID,
  input  [11:0] ring_tx_snoop_bits_TxnID,
  input  [10:0] ring_tx_snoop_bits_SrcID,
  input  [10:0] ring_tx_snoop_bits_TgtID,
  input  [3:0]  ring_tx_snoop_bits_QoS
);

  // PDC 线交叉直连（dev.tx → icn.rx，icn.tx → dev.rx）
  SocketDevSide dev (
    .clock                       (clock),
    .reset                       (reset),
    .io_icn_rx_req_ready         (l2_rx_req_ready),
    .io_icn_rx_req_valid         (l2_rx_req_valid),
    .io_icn_rx_req_bits_ExpCompAck(l2_rx_req_bits_ExpCompAck),
    .io_icn_rx_req_bits_Excl     (l2_rx_req_bits_Excl),
    .io_icn_rx_req_bits_SnpAttr  (l2_rx_req_bits_SnpAttr),
    .io_icn_rx_req_bits_MemAttr  (l2_rx_req_bits_MemAttr),
    .io_icn_rx_req_bits_Order    (l2_rx_req_bits_Order),
    .io_icn_rx_req_bits_Addr     (l2_rx_req_bits_Addr),
    .io_icn_rx_req_bits_Size     (l2_rx_req_bits_Size),
    .io_icn_rx_req_bits_Opcode   (l2_rx_req_bits_Opcode),
    .io_icn_rx_req_bits_TxnID    (l2_rx_req_bits_TxnID),
    .io_icn_rx_req_bits_SrcID    (l2_rx_req_bits_SrcID),
    .io_icn_rx_req_bits_TgtID    (l2_rx_req_bits_TgtID),
    .io_icn_rx_req_bits_QoS      (l2_rx_req_bits_QoS),
    .io_icn_rx_resp_ready        (l2_rx_resp_ready),
    .io_icn_rx_resp_valid        (l2_rx_resp_valid),
    .io_icn_rx_resp_bits_DBID    (l2_rx_resp_bits_DBID),
    .io_icn_rx_resp_bits_CBusy   (l2_rx_resp_bits_CBusy),
    .io_icn_rx_resp_bits_FwdState(l2_rx_resp_bits_FwdState),
    .io_icn_rx_resp_bits_Resp    (l2_rx_resp_bits_Resp),
    .io_icn_rx_resp_bits_RespErr (l2_rx_resp_bits_RespErr),
    .io_icn_rx_resp_bits_Opcode  (l2_rx_resp_bits_Opcode),
    .io_icn_rx_resp_bits_TxnID   (l2_rx_resp_bits_TxnID),
    .io_icn_rx_resp_bits_SrcID   (l2_rx_resp_bits_SrcID),
    .io_icn_rx_resp_bits_TgtID   (l2_rx_resp_bits_TgtID),
    .io_icn_rx_resp_bits_QoS     (l2_rx_resp_bits_QoS),
    .io_icn_rx_data_ready        (l2_rx_data_ready),
    .io_icn_rx_data_valid        (l2_rx_data_valid),
    .io_icn_rx_data_bits_Data    (l2_rx_data_bits_Data),
    .io_icn_rx_data_bits_BE      (l2_rx_data_bits_BE),
    .io_icn_rx_data_bits_DataID  (l2_rx_data_bits_DataID),
    .io_icn_rx_data_bits_DBID    (l2_rx_data_bits_DBID),
    .io_icn_rx_data_bits_CBusy   (l2_rx_data_bits_CBusy),
    .io_icn_rx_data_bits_DataSource(l2_rx_data_bits_DataSource),
    .io_icn_rx_data_bits_Resp    (l2_rx_data_bits_Resp),
    .io_icn_rx_data_bits_RespErr (l2_rx_data_bits_RespErr),
    .io_icn_rx_data_bits_Opcode  (l2_rx_data_bits_Opcode),
    .io_icn_rx_data_bits_HomeNID (l2_rx_data_bits_HomeNID),
    .io_icn_rx_data_bits_TxnID   (l2_rx_data_bits_TxnID),
    .io_icn_rx_data_bits_SrcID   (l2_rx_data_bits_SrcID),
    .io_icn_rx_data_bits_TgtID   (l2_rx_data_bits_TgtID),
    .io_icn_rx_data_bits_QoS     (l2_rx_data_bits_QoS),
    .io_icn_tx_resp_ready        (l2_tx_resp_ready),
    .io_icn_tx_resp_valid        (l2_tx_resp_valid),
    .io_icn_tx_resp_bits_DBID    (l2_tx_resp_bits_DBID),
    .io_icn_tx_resp_bits_CBusy   (l2_tx_resp_bits_CBusy),
    .io_icn_tx_resp_bits_FwdState(l2_tx_resp_bits_FwdState),
    .io_icn_tx_resp_bits_Resp    (l2_tx_resp_bits_Resp),
    .io_icn_tx_resp_bits_RespErr (l2_tx_resp_bits_RespErr),
    .io_icn_tx_resp_bits_Opcode  (l2_tx_resp_bits_Opcode),
    .io_icn_tx_resp_bits_TxnID   (l2_tx_resp_bits_TxnID),
    .io_icn_tx_resp_bits_SrcID   (l2_tx_resp_bits_SrcID),
    .io_icn_tx_resp_bits_QoS     (l2_tx_resp_bits_QoS),
    .io_icn_tx_data_ready        (l2_tx_data_ready),
    .io_icn_tx_data_valid        (l2_tx_data_valid),
    .io_icn_tx_data_bits_Data    (l2_tx_data_bits_Data),
    .io_icn_tx_data_bits_BE      (l2_tx_data_bits_BE),
    .io_icn_tx_data_bits_DataID  (l2_tx_data_bits_DataID),
    .io_icn_tx_data_bits_DBID    (l2_tx_data_bits_DBID),
    .io_icn_tx_data_bits_CBusy   (l2_tx_data_bits_CBusy),
    .io_icn_tx_data_bits_DataSource(l2_tx_data_bits_DataSource),
    .io_icn_tx_data_bits_Resp    (l2_tx_data_bits_Resp),
    .io_icn_tx_data_bits_RespErr (l2_tx_data_bits_RespErr),
    .io_icn_tx_data_bits_Opcode  (l2_tx_data_bits_Opcode),
    .io_icn_tx_data_bits_HomeNID (l2_tx_data_bits_HomeNID),
    .io_icn_tx_data_bits_TxnID   (l2_tx_data_bits_TxnID),
    .io_icn_tx_data_bits_SrcID   (l2_tx_data_bits_SrcID),
    .io_icn_tx_data_bits_TgtID   (l2_tx_data_bits_TgtID),
    .io_icn_tx_data_bits_QoS     (l2_tx_data_bits_QoS),
    .io_icn_tx_snoop_ready       (l2_tx_snoop_ready),
    .io_icn_tx_snoop_valid       (l2_tx_snoop_valid),
    .io_icn_tx_snoop_bits_RetToSrc(l2_tx_snoop_bits_RetToSrc),
    .io_icn_tx_snoop_bits_DoNotGoToSD(l2_tx_snoop_bits_DoNotGoToSD),
    .io_icn_tx_snoop_bits_Addr   (l2_tx_snoop_bits_Addr),
    .io_icn_tx_snoop_bits_Opcode (l2_tx_snoop_bits_Opcode),
    .io_icn_tx_snoop_bits_FwdTxnID(l2_tx_snoop_bits_FwdTxnID),
    .io_icn_tx_snoop_bits_FwdNID (l2_tx_snoop_bits_FwdNID),
    .io_icn_tx_snoop_bits_TxnID  (l2_tx_snoop_bits_TxnID),
    .io_icn_tx_snoop_bits_SrcID  (l2_tx_snoop_bits_SrcID),
    .io_icn_tx_snoop_bits_QoS    (l2_tx_snoop_bits_QoS),
    .io_socket_sync_tx_req_valid (sync_ij_req_valid),
    .io_socket_sync_tx_req_bits  (sync_ij_req_bits),
    .io_socket_sync_tx_req_grant (sync_ij_req_grant),
    .io_socket_sync_tx_rsp_valid (sync_ij_rsp_valid),
    .io_socket_sync_tx_rsp_bits  (sync_ij_rsp_bits),
    .io_socket_sync_tx_rsp_grant (sync_ij_rsp_grant),
    .io_socket_sync_tx_dat_valid (sync_ij_dat_valid),
    .io_socket_sync_tx_dat_bits  (sync_ij_dat_bits),
    .io_socket_sync_tx_dat_grant (sync_ij_dat_grant),
    .io_socket_sync_rx_req_valid (sync_ej_req_valid),
    .io_socket_sync_rx_req_bits  (sync_ej_req_bits),
    .io_socket_sync_rx_req_grant (sync_ej_req_grant),
    .io_socket_sync_rx_rsp_valid (sync_ej_rsp_valid),
    .io_socket_sync_rx_rsp_bits  (sync_ej_rsp_bits),
    .io_socket_sync_rx_rsp_grant (sync_ej_rsp_grant),
    .io_socket_sync_rx_dat_valid (sync_ej_dat_valid),
    .io_socket_sync_rx_dat_bits  (sync_ej_dat_bits),
    .io_socket_sync_rx_dat_grant (sync_ej_dat_grant),
    .io_socket_sync_rx_snp_valid (sync_ej_snp_valid),
    .io_socket_sync_rx_snp_bits  (sync_ej_snp_bits),
    .io_socket_sync_rx_snp_grant (sync_ej_snp_grant)
  );

  SocketIcnSide icn (
    .clock                       (clock),
    .reset                       (reset),
    .io_dev_tx_req_ready         (ring_rx_req_ready),
    .io_dev_tx_req_valid         (ring_rx_req_valid),
    .io_dev_tx_req_bits_ExpCompAck(ring_rx_req_bits_ExpCompAck),
    .io_dev_tx_req_bits_Excl     (ring_rx_req_bits_Excl),
    .io_dev_tx_req_bits_SnpAttr  (ring_rx_req_bits_SnpAttr),
    .io_dev_tx_req_bits_MemAttr  (ring_rx_req_bits_MemAttr),
    .io_dev_tx_req_bits_Order    (ring_rx_req_bits_Order),
    .io_dev_tx_req_bits_Addr     (ring_rx_req_bits_Addr),
    .io_dev_tx_req_bits_Size     (ring_rx_req_bits_Size),
    .io_dev_tx_req_bits_Opcode   (ring_rx_req_bits_Opcode),
    .io_dev_tx_req_bits_TxnID    (ring_rx_req_bits_TxnID),
    .io_dev_tx_req_bits_SrcID    (ring_rx_req_bits_SrcID),
    .io_dev_tx_req_bits_TgtID    (ring_rx_req_bits_TgtID),
    .io_dev_tx_req_bits_QoS      (ring_rx_req_bits_QoS),
    .io_dev_tx_resp_ready        (ring_rx_resp_ready),
    .io_dev_tx_resp_valid        (ring_rx_resp_valid),
    .io_dev_tx_resp_bits_DBID    (ring_rx_resp_bits_DBID),
    .io_dev_tx_resp_bits_CBusy   (ring_rx_resp_bits_CBusy),
    .io_dev_tx_resp_bits_FwdState(ring_rx_resp_bits_FwdState),
    .io_dev_tx_resp_bits_Resp    (ring_rx_resp_bits_Resp),
    .io_dev_tx_resp_bits_RespErr (ring_rx_resp_bits_RespErr),
    .io_dev_tx_resp_bits_Opcode  (ring_rx_resp_bits_Opcode),
    .io_dev_tx_resp_bits_TxnID   (ring_rx_resp_bits_TxnID),
    .io_dev_tx_resp_bits_SrcID   (ring_rx_resp_bits_SrcID),
    .io_dev_tx_resp_bits_TgtID   (ring_rx_resp_bits_TgtID),
    .io_dev_tx_resp_bits_QoS     (ring_rx_resp_bits_QoS),
    .io_dev_tx_data_ready        (ring_rx_data_ready),
    .io_dev_tx_data_valid        (ring_rx_data_valid),
    .io_dev_tx_data_bits_Data    (ring_rx_data_bits_Data),
    .io_dev_tx_data_bits_BE      (ring_rx_data_bits_BE),
    .io_dev_tx_data_bits_DataID  (ring_rx_data_bits_DataID),
    .io_dev_tx_data_bits_DBID    (ring_rx_data_bits_DBID),
    .io_dev_tx_data_bits_CBusy   (ring_rx_data_bits_CBusy),
    .io_dev_tx_data_bits_DataSource(ring_rx_data_bits_DataSource),
    .io_dev_tx_data_bits_Resp    (ring_rx_data_bits_Resp),
    .io_dev_tx_data_bits_RespErr (ring_rx_data_bits_RespErr),
    .io_dev_tx_data_bits_Opcode  (ring_rx_data_bits_Opcode),
    .io_dev_tx_data_bits_HomeNID (ring_rx_data_bits_HomeNID),
    .io_dev_tx_data_bits_TxnID   (ring_rx_data_bits_TxnID),
    .io_dev_tx_data_bits_SrcID   (ring_rx_data_bits_SrcID),
    .io_dev_tx_data_bits_TgtID   (ring_rx_data_bits_TgtID),
    .io_dev_tx_data_bits_QoS     (ring_rx_data_bits_QoS),
    .io_dev_rx_req_ready         (ring_tx_req_ready),
    .io_dev_rx_req_valid         (ring_tx_req_valid),
    .io_dev_rx_req_bits_ExpCompAck(ring_tx_req_bits_ExpCompAck),
    .io_dev_rx_req_bits_Excl     (ring_tx_req_bits_Excl),
    .io_dev_rx_req_bits_SnpAttr  (ring_tx_req_bits_SnpAttr),
    .io_dev_rx_req_bits_MemAttr  (ring_tx_req_bits_MemAttr),
    .io_dev_rx_req_bits_Order    (ring_tx_req_bits_Order),
    .io_dev_rx_req_bits_Addr     (ring_tx_req_bits_Addr),
    .io_dev_rx_req_bits_Size     (ring_tx_req_bits_Size),
    .io_dev_rx_req_bits_Opcode   (ring_tx_req_bits_Opcode),
    .io_dev_rx_req_bits_TxnID    (ring_tx_req_bits_TxnID),
    .io_dev_rx_req_bits_SrcID    (ring_tx_req_bits_SrcID),
    .io_dev_rx_req_bits_TgtID    (ring_tx_req_bits_TgtID),
    .io_dev_rx_req_bits_QoS      (ring_tx_req_bits_QoS),
    .io_dev_rx_resp_ready        (ring_tx_resp_ready),
    .io_dev_rx_resp_valid        (ring_tx_resp_valid),
    .io_dev_rx_resp_bits_DBID    (ring_tx_resp_bits_DBID),
    .io_dev_rx_resp_bits_CBusy   (ring_tx_resp_bits_CBusy),
    .io_dev_rx_resp_bits_FwdState(ring_tx_resp_bits_FwdState),
    .io_dev_rx_resp_bits_Resp    (ring_tx_resp_bits_Resp),
    .io_dev_rx_resp_bits_RespErr (ring_tx_resp_bits_RespErr),
    .io_dev_rx_resp_bits_Opcode  (ring_tx_resp_bits_Opcode),
    .io_dev_rx_resp_bits_TxnID   (ring_tx_resp_bits_TxnID),
    .io_dev_rx_resp_bits_SrcID   (ring_tx_resp_bits_SrcID),
    .io_dev_rx_resp_bits_TgtID   (ring_tx_resp_bits_TgtID),
    .io_dev_rx_resp_bits_QoS     (ring_tx_resp_bits_QoS),
    .io_dev_rx_data_ready        (ring_tx_data_ready),
    .io_dev_rx_data_valid        (ring_tx_data_valid),
    .io_dev_rx_data_bits_Data    (ring_tx_data_bits_Data),
    .io_dev_rx_data_bits_BE      (ring_tx_data_bits_BE),
    .io_dev_rx_data_bits_DataID  (ring_tx_data_bits_DataID),
    .io_dev_rx_data_bits_DBID    (ring_tx_data_bits_DBID),
    .io_dev_rx_data_bits_CBusy   (ring_tx_data_bits_CBusy),
    .io_dev_rx_data_bits_DataSource(ring_tx_data_bits_DataSource),
    .io_dev_rx_data_bits_Resp    (ring_tx_data_bits_Resp),
    .io_dev_rx_data_bits_RespErr (ring_tx_data_bits_RespErr),
    .io_dev_rx_data_bits_Opcode  (ring_tx_data_bits_Opcode),
    .io_dev_rx_data_bits_HomeNID (ring_tx_data_bits_HomeNID),
    .io_dev_rx_data_bits_TxnID   (ring_tx_data_bits_TxnID),
    .io_dev_rx_data_bits_SrcID   (ring_tx_data_bits_SrcID),
    .io_dev_rx_data_bits_TgtID   (ring_tx_data_bits_TgtID),
    .io_dev_rx_data_bits_QoS     (ring_tx_data_bits_QoS),
    .io_dev_rx_snoop_ready       (ring_tx_snoop_ready),
    .io_dev_rx_snoop_valid       (ring_tx_snoop_valid),
    .io_dev_rx_snoop_bits_RetToSrc(ring_tx_snoop_bits_RetToSrc),
    .io_dev_rx_snoop_bits_DoNotGoToSD(ring_tx_snoop_bits_DoNotGoToSD),
    .io_dev_rx_snoop_bits_Addr   (ring_tx_snoop_bits_Addr),
    .io_dev_rx_snoop_bits_Opcode (ring_tx_snoop_bits_Opcode),
    .io_dev_rx_snoop_bits_FwdTxnID(ring_tx_snoop_bits_FwdTxnID),
    .io_dev_rx_snoop_bits_FwdNID (ring_tx_snoop_bits_FwdNID),
    .io_dev_rx_snoop_bits_TxnID  (ring_tx_snoop_bits_TxnID),
    .io_dev_rx_snoop_bits_SrcID  (ring_tx_snoop_bits_SrcID),
    .io_dev_rx_snoop_bits_TgtID  (ring_tx_snoop_bits_TgtID),
    .io_dev_rx_snoop_bits_QoS    (ring_tx_snoop_bits_QoS),
    .io_socket_sync_tx_req_valid (sync_ej_req_valid),
    .io_socket_sync_tx_req_bits  (sync_ej_req_bits),
    .io_socket_sync_tx_req_grant (sync_ej_req_grant),
    .io_socket_sync_tx_rsp_valid (sync_ej_rsp_valid),
    .io_socket_sync_tx_rsp_bits  (sync_ej_rsp_bits),
    .io_socket_sync_tx_rsp_grant (sync_ej_rsp_grant),
    .io_socket_sync_tx_dat_valid (sync_ej_dat_valid),
    .io_socket_sync_tx_dat_bits  (sync_ej_dat_bits),
    .io_socket_sync_tx_dat_grant (sync_ej_dat_grant),
    .io_socket_sync_tx_snp_valid (sync_ej_snp_valid),
    .io_socket_sync_tx_snp_bits  (sync_ej_snp_bits),
    .io_socket_sync_tx_snp_grant (sync_ej_snp_grant),
    .io_socket_sync_rx_req_valid (sync_ij_req_valid),
    .io_socket_sync_rx_req_bits  (sync_ij_req_bits),
    .io_socket_sync_rx_req_grant (sync_ij_req_grant),
    .io_socket_sync_rx_rsp_valid (sync_ij_rsp_valid),
    .io_socket_sync_rx_rsp_bits  (sync_ij_rsp_bits),
    .io_socket_sync_rx_rsp_grant (sync_ij_rsp_grant),
    .io_socket_sync_rx_dat_valid (sync_ij_dat_valid),
    .io_socket_sync_rx_dat_bits  (sync_ij_dat_bits),
    .io_socket_sync_rx_dat_grant (sync_ij_dat_grant)
  );

  // inject（L2→环）PDC 线
  wire        sync_ij_req_valid;
  wire [104:0] sync_ij_req_bits;
  wire        sync_ij_req_grant;
  wire        sync_ij_rsp_valid;
  wire [65:0] sync_ij_rsp_bits;
  wire        sync_ij_rsp_grant;
  wire        sync_ij_dat_valid;
  wire [374:0] sync_ij_dat_bits;
  wire        sync_ij_dat_grant;
  // eject（环→L2）PDC 线
  wire        sync_ej_req_valid;
  wire [104:0] sync_ej_req_bits;
  wire        sync_ej_req_grant;
  wire        sync_ej_rsp_valid;
  wire [65:0] sync_ej_rsp_bits;
  wire        sync_ej_rsp_grant;
  wire        sync_ej_dat_valid;
  wire [374:0] sync_ej_dat_bits;
  wire        sync_ej_dat_grant;
  wire        sync_ej_snp_valid;
  wire [112:0] sync_ej_snp_bits;
  wire        sync_ej_snp_grant;

endmodule
